In [95]:
import pandas as pd
df=pd.read_csv('data.csv')
df

,NDB_No,Short_Description,Water_In_Grams,Energy_In_Kilogram_Calorie,Protein_In_Grams,Lipid_Tot_In_Grams,Ash_In_Grams,Carbohydrate_In_Grams,Fiber_TD_In_Grams,Sugar_Tot_In_Grams,...,Vit_K_In_Micrograms,FA_Sat_In_Grams,FA_Mono_In_Grams,FA_Poly_In_Grams,Cholesterol_In_Miligrams,Gram_Weight_1,Gram_Weight_Descritpion_1,Gram_Weight_2,Gram_Weight_Description_2,Refuse_Percent
0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,...,4.6,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0
3,1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0
4,1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,83110,"MACKEREL,SALTED",43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,7.8,7.148,8.320,6.210,95.0,80.00,"1 piece, (5-1/2"" x 1-1/2"" x 1/2"")",17.0,"1 cubic inch, boneless",0.0
8786,90240,"SCALLOP,(BAY&SEA),CKD,STMD",70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.0,0.218,0.082,0.222,41.0,85.00,3 oz,NaN,NaN,0.0
8787,90480,"SYRUP,CANE",26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.000,0.000,0.000,0.0,21.00,1 serving,NaN,NaN,0.0
8788,90560,"SNAIL,RAW",79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.1,0.361,0.259,0.252,50.0,85.00,3 oz,NaN,NaN,0.0
8789,93600,"TURTLE,GREEN,RAW",78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.1,0.127,0.088,0.170,50.0,85.00,3 oz,NaN,NaN,0.0

In [96]:
df.columns

Index(['NDB_No', 'Short_Description', 'Water_In_Grams',
       'Energy_In_Kilogram_Calorie', 'Protein_In_Grams', 'Lipid_Tot_In_Grams',
       'Ash_In_Grams', 'Carbohydrate_In_Grams', 'Fiber_TD_In_Grams',
       'Sugar_Tot_In_Grams', 'Calcium_In_Miligrams', 'Iron_In_Miligrams',
       'Magnesium_In_Miligrams', 'Phosphorus_In_Miligrams',
       'Potassium_In_Miligrams', 'Sodium_In_Miligrams', 'Zinc_In_Miligrams',
       'Copper_In_Miligrams', 'Manganese_In_Miligrams',
       'Selenium_In_Micrograms', 'Vit_C_In_Miligrams', 'Thiamin_In_Miligrams',
       'Riboflavin_In_Miligrams', 'Niacin_In_Miligrams',
       'Panto_Acid_In_Miligrams', 'Vit_B6_In_Miligrams',
       'Folate_Tot_In_Micrograms', 'Folic_Acid_In_Micrograms',
       'Food_Folate_In_Micrograms', 'Folate_DFE_In_Micrograms',
       'Choline_Tot_In_Miligrams', 'Vit_B12_In_Micrograms',
       'Vit_A_In_International_Unit', 'Vit_A_In_Retinol_Activity_Equivalents',
       'Retinol_In_Micrograms', 'Alpha_Carot_In_Micrograms',
       'Beta_Carot_In_Micrograms', 'Beta_Crypt_In_Micrograms',
       'Lycopene_In_Micrograms', 'Lut_And_Zea_In_Micrograms',
       'Vit_E_In_Miligrams', 'Vit_D_In_Micrograms',
       'Vit_D_In_International_Unit', 'Vit_K_In_Micrograms', 'FA_Sat_In_Grams',
       'FA_Mono_In_Grams', 'FA_Poly_In_Grams', 'Cholesterol_In_Miligrams',
       'Gram_Weight_1', 'Gram_Weight_Descritpion_1', 'Gram_Weight_2',
       'Gram_Weight_Description_2', 'Refuse_Percent'],
      dtype='object')

In [97]:
df1 = df.drop(['NDB_No','Water_In_Grams','Ash_In_Grams','Calcium_In_Miligrams','Magnesium_In_Miligrams','Phosphorus_In_Miligrams','Potassium_In_Miligrams','Zinc_In_Miligrams','Copper_In_Miligrams', 'Manganese_In_Miligrams',
       'Selenium_In_Micrograms', 'Vit_C_In_Miligrams', 'Thiamin_In_Miligrams',
       'Riboflavin_In_Miligrams', 'Niacin_In_Miligrams',
       'Panto_Acid_In_Miligrams', 'Vit_B6_In_Miligrams',
       'Folate_Tot_In_Micrograms', 'Folic_Acid_In_Micrograms',
       'Food_Folate_In_Micrograms', 'Folate_DFE_In_Micrograms',
       'Choline_Tot_In_Miligrams', 'Vit_B12_In_Micrograms',
       'Vit_A_In_International_Unit', 'Vit_A_In_Retinol_Activity_Equivalents',
       'Retinol_In_Micrograms', 'Alpha_Carot_In_Micrograms',
       'Beta_Carot_In_Micrograms', 'Beta_Crypt_In_Micrograms',
       'Lycopene_In_Micrograms', 'Lut_And_Zea_In_Micrograms',
       'Vit_E_In_Miligrams', 'Vit_D_In_Micrograms',
       'Vit_D_In_International_Unit', 'Vit_K_In_Micrograms','FA_Mono_In_Grams', 'FA_Poly_In_Grams','Gram_Weight_1', 'Gram_Weight_Descritpion_1', 'Gram_Weight_2',
       'Gram_Weight_Description_2', 'Refuse_Percent'],axis = 1)
df1

,Short_Description,Energy_In_Kilogram_Calorie,Protein_In_Grams,Lipid_Tot_In_Grams,Carbohydrate_In_Grams,Fiber_TD_In_Grams,Sugar_Tot_In_Grams,Iron_In_Miligrams,Sodium_In_Miligrams,FA_Sat_In_Grams,Cholesterol_In_Miligrams
0,"BUTTER,WITH SALT",717,0.85,81.11,0.06,0.0,0.06,0.02,643.0,51.368,215.0
1,"BUTTER,WHIPPED,W/ SALT",718,0.49,78.30,2.87,0.0,0.06,0.05,583.0,45.390,225.0
2,"BUTTER OIL,ANHYDROUS",876,0.28,99.48,0.00,0.0,0.00,0.00,2.0,61.924,256.0
3,"CHEESE,BLUE",353,21.40,28.74,2.34,0.0,0.50,0.31,1146.0,18.669,75.0
4,"CHEESE,BRICK",371,23.24,29.68,2.79,0.0,0.51,0.43,560.0,18.764,94.0
...,...,...,...,...,...,...,...,...,...,...,...
8785,"MACKEREL,SALTED",305,18.50,25.10,0.00,0.0,0.00,1.40,4450.0,7.148,95.0
8786,"SCALLOP,(BAY&SEA),CKD,STMD",111,20.54,0.84,5.41,0.0,0.00,0.58,667.0,0.218,41.0
8787,"SYRUP,CANE",269,0.00,0.00,73.14,0.0,73.20,3.60,58.0,0.000,0.0
8788,"SNAIL,RAW",90,16.10,1.40,2.00,0.0,0.00,3.50,70.0,0.361,50.0
8789,"TURTLE,GREEN,RAW",89,19.80,0.50,0.00,0.0,0.00,1.40,68.0,0.127,50.0

In [98]:
df1['Added  Sugar(g) per 100 g'] = [0]* len(df1)
df1['trans fat (g) _per 100 g'] = [0]* len(df1)
df1.to_csv('real_data.csv')

In [99]:
x=pd.read_csv('real_data1.csv')
A=x.drop(['Unnamed: 0'] ,axis=1)
B=pd.read_csv('final_data.csv')
B=B.drop(['Unnamed: 0'], axis=1)
columns_order = B.columns

# Reorder the columns of df2 to match the order of df1's columns
A= A.reindex(columns=columns_order)
A

,Food_name,Energy(kcal)_per 100 g,Protein(g) per 100 g,Carbohydrate(g) per 100 g,total sugar(g) per 100 g,Added Sugar(g) per 100 g,fibre(g) per 100 g,total fat (g) per 100 gms,saturated fat (g) per 100 g,trans fat (g) _per 100 g,Sodium(mg) per 100 g,iron (mg) per 100 gm,Cholesterol per 100 mg
0,"BUTTER,WITH SALT",717,0.85,0.06,0.06,0,0.0,81.11,51.368,0,643.0,0.02,215.0
1,"BUTTER,WHIPPED,W/ SALT",718,0.49,2.87,0.06,0,0.0,78.30,45.390,0,583.0,0.05,225.0
2,"BUTTER OIL,ANHYDROUS",876,0.28,0.00,0.00,0,0.0,99.48,61.924,0,2.0,0.00,256.0
3,"CHEESE,BLUE",353,21.40,2.34,0.50,0,0.0,28.74,18.669,0,1146.0,0.31,75.0
4,"CHEESE,BRICK",371,23.24,2.79,0.51,0,0.0,29.68,18.764,0,560.0,0.43,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,"MACKEREL,SALTED",305,18.50,0.00,0.00,0,0.0,25.10,7.148,0,4450.0,1.40,95.0
8786,"SCALLOP,(BAY&SEA),CKD,STMD",111,20.54,5.41,0.00,0,0.0,0.84,0.218,0,667.0,0.58,41.0
8787,"SYRUP,CANE",269,0.00,73.14,73.20,0,0.0,0.00,0.000,0,58.0,3.60,0.0
8788,"SNAIL,RAW",90,16.10,2.00,0.00,0,0.0,1.40,0.361,0,70.0,3.50,50.0
8789,"TURTLE,GREEN,RAW",89,19.80,0.00,0.00,0,0.0,0.50,0.127,0,68.0,1.40,50.0

In [100]:
len(A.columns)

13

In [101]:
B.columns

Index(['Food_name', 'Energy(kcal)_per 100 g', 'Protein(g) per 100 g',
       'Carbohydrate(g) per 100 g', 'total sugar(g) per 100 g',
       'Added  Sugar(g) per 100 g', 'fibre(g) per 100 g',
       'total fat (g) per 100 gms', 'saturated fat (g) per 100 g',
       'trans fat (g) _per 100 g', 'Sodium(mg) per 100 g',
       'iron (mg) per 100 gm', 'Cholesterol per 100 mg'],
      dtype='object')

In [102]:
len(B.columns)

13

In [103]:
import pandas as pd

# Assuming df1 and df3 are your DataFrames

# Concatenate df1 and df3 along the row axis
C = pd.concat([A, B], axis=0)

# Now concatenated_df contains both DataFrames stacked vertically
C.to_csv('my_data.csv')